import { Rubik } from "next/font/google";
import Navbar from "./ui/navbar/Navbar";
import "./globals.css";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <Navbar />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
